<?php

class AddAnos extends Seeder {

public function run() {
    DB::table('anos')->delete(); // deleting old records.

    Anos::create( [
    'ano' =>'1977'
    ] );
    Anos::create( [
    'ano' =>'1978'
    ] );
    Anos::create( [
    'ano' =>'1979'
    ] );
    Anos::create( [
    'ano' =>'1980'
    ] );
    Anos::create( [
    'ano' =>'1981'
    ] );
    Anos::create( [
    'ano' =>'1982'
    ] );
    Anos::create( [
    'ano' =>'1983'
    ] );
    Anos::create( [
    'ano' =>'1984'
    ] );
    Anos::create( [
    'ano' =>'1985'
    ] );
    Anos::create( [
    'ano' =>'1986'
    ] );
    Anos::create( [
    'ano' =>'1987'
    ] );
    Anos::create( [
    'ano' =>'1988'
    ] );
    Anos::create( [
    'ano' =>'1989'
    ] );
    Anos::create( [
    'ano' =>'1990'
    ] );
    Anos::create( [
    'ano' =>'1991'
    ] );
    Anos::create( [
    'ano' =>'1992'
    ] );
    Anos::create( [
    'ano' =>'1993'
    ] );
    Anos::create( [
    'ano' =>'1994'
    ] );
    Anos::create( [
    'ano' =>'1995'
    ] );
    Anos::create( [
    'ano' =>'1996'
    ] );
    Anos::create( [
    'ano' =>'1997'
    ] );
    Anos::create( [
    'ano' =>'1998'
    ] );
    Anos::create( [
    'ano' =>'1999'
    ] );
    Anos::create( [
    'ano' =>'2000'
    ] );
    Anos::create( [
    'ano' =>'2001'
    ] );
    Anos::create( [
    'ano' =>'2002'
    ] );
    Anos::create( [
    'ano' =>'2003'
    ] );
    Anos::create( [
    'ano' =>'2004'
    ] );
    Anos::create( [
    'ano' =>'2005'
    ] );
    Anos::create( [
    'ano' =>'2006'
    ] );
    Anos::create( [
    'ano' =>'2007'
    ] );
    Anos::create( [
    'ano' =>'2008'
    ] );
    Anos::create( [
    'ano' =>'2009'
    ] );
    Anos::create( [
    'ano' =>'2010'
    ] );
    Anos::create( [
    'ano' =>'2011'
    ] );
    Anos::create( [
    'ano' =>'2012'
    ] );
    Anos::create( [
    'ano' =>'2013'
    ] );
    Anos::create( [
    'ano' =>'2014'
    ] );
    Anos::create( [
    'ano' =>'2015'
    ] );
    Anos::create( [
    'ano' =>'2016'
    ] );
    Anos::create( [
    'ano' =>'2017'
    ] );
    Anos::create( [
    'ano' =>'2018'
    ] );
    }

}